openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Support Diagnostics API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Support Diagnostics
  description: Manages support diagnostics for the array, including performing diagnostics tasks, running tests, finding problems and giving remediation. The diagnostics tool provides a way to test the array components and generate a report of the results.
paths:
  /api/2.26/support-diagnostics:
    get:
      tags:
      - Support Diagnostics
      summary: Pure Storage GET Diagnostics List
      description: 'Lists the support diagnostics tasks.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportDiagnosticsGetResponse'
    post:
      tags:
      - Support Diagnostics
      summary: Pure Storage Start a Diagnostic Task
      description: 'Creates a diagnostics task for a given time interval.

        If `start_time` is not provided, defaults to Current System Time - 1 hour.

        If `end_time` is not provided, defaults to Current System Time.

        If a task is already running, an error is returned.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Analysis_period_end_time'
      - $ref: '#/components/parameters/Analysis_period_start_time'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportDiagnosticsGetResponse'
        '403':
          description: Another instance is already running
          content: {}
  /api/2.26/support-diagnostics/details:
    get:
      tags:
      - Support Diagnostics
      summary: Pure Storage GET Diagnostics Details
      description: 'Lists the diagnostics tasks details.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportDiagnosticsDetailsGetResponse'
  /api/2.26/support-diagnostics/settings:
    get:
      tags:
      - Support Diagnostics
      summary: Pure Storage List Diagnostics Tools Version and Last Updated Date
      description: 'Displays diagnostics tools version and last updated date.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportDiagnosticsSettingsGetResponse'
    patch:
      tags:
      - Support Diagnostics
      summary: Pure Storage Update Diagnostics Tools
      description: 'Update diagnostics tools from downloaded bundle.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      responses:
        '200':
          description: 'The diagnostics tools were updated successfully.

            '
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportDiagnosticsSettingsResponse'
components:
  parameters:
    Analysis_period_end_time:
      name: analysis_period_end_time
      in: query
      description: 'When the analysis time window ends (in milliseconds since epoch).

        '
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1514764800000
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Analysis_period_start_time:
      name: analysis_period_start_time
      in: query
      description: 'When the analysis time window starts (in milliseconds since epoch).

        '
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1514764800000
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    SupportDiagnosticsDetailsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SupportDiagnosticsDetailsResponse'
    _start_end_time:
      description: A resource with a start time and end time.
      type: object
      properties:
        end_time:
          description: End time in milliseconds since the UNIX epoch.
          type: integer
          format: int64
          example: 1567026888000
          x-minimum: 0
        start_time:
          description: Start time in milliseconds since the UNIX epoch.
          type: integer
          format: int64
          example: 1567026779000
          x-minimum: 0
    SupportDiagnosticsDetailsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SupportDiagnosticsDetails'
    SupportDiagnosticsSettingsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SupportDiagnosticsSettings'
    SupportDiagnosticsSettingsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SupportDiagnosticsSettingsResponse'
    _supportDiagnosticsSeverityCount:
      type: object
      properties:
        count:
          description: 'Count of the corresponding severity.

            '
          type: integer
          example: 1
        severity:
          description: 'Severity level of the test.

            Valid values include `info`, `warning`, `critical`.

            '
          type: string
          example: critical
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    SupportDiagnostics:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - type: object
        properties:
          analysis_period:
            $ref: '#/components/schemas/_start_end_time'
          index:
            description: The unique index of the task.
            type: integer
            format: int64
            readOnly: true
            example: 1
          severity_count:
            description: 'List of severity counts.

              '
            type: array
            items:
              $ref: '#/components/schemas/_supportDiagnosticsSeverityCount'
          start_time:
            description: Start time in milliseconds since the UNIX epoch.
            type: integer
            format: int64
            example: 1567026779000
            x-minimum: 0
          status:
            description: 'Status of the diagnostics.

              A status of `running` indicates that the diagnostics is still running.

              A status of `completed` indicates that the diagnostics has completed.

              A status of `failed` indicates that the diagnostics has failed.

              '
            type: string
            example: completed
          task_id:
            description: 'A globally unique, system-generated ID. The ID cannot be modified.

              '
            type: string
            readOnly: true
          version:
            description: Version of diagnostics tool.
            type: string
            example: 1.0.4.0
    SupportDiagnosticsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SupportDiagnosticsResponse'
    SupportDiagnosticsDetails:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - type: object
        properties:
          index:
            description: 'The unique index of the test. It will be of the format A.B

              where A is the task index and B is the test index.

              '
            type: number
            readOnly: true
            example: 1.1
          result_details:
            description: 'More details related to the test.

              This field can provide remediation information as well.

              '
            type: string
            example: Subnets does not exist for Mgmt services.
          severity:
            description: 'Severity level of the test.

              Valid values include `info`, `warning`, `critical`.

              '
            type: string
            example: critical
          task_id:
            description: 'The task ID of the diagnostics for which this refers to.

              '
            type: string
            readOnly: true
          test_name:
            description: 'Name of the test that was performed.

              '
            type: string
            example: Subnet Check For Management Service
          test_type:
            description: 'Category to which the test belongs to.

              '
            type: string
            example: Generic
    SupportDiagnosticsSettings:
      description: 'Diagnostics tools

        '
      type: object
      properties:
        last_updated:
          description: 'Date the diagnostics tool was last updated.

            '
          type: integer
          format: int64
          example: 1672531200000
        version:
          description: 'Version of the diagnostics tool.

            '
          type: string
          readOnly: true
          example: 1.0.0
    SupportDiagnosticsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SupportDiagnostics'
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
