openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Audit Log Target for File Systems API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Audit Log Target for File Systems
  description: View and manage audit log targets that are filesystems. These are filesystems where audit logs will be stored, and they may be configured in audit policies.
paths:
  /api/2.26/log-targets/file-systems:
    get:
      tags:
      - Audit Log Target for File Systems
      summary: Pure Storage GET Log-target-file-systems
      description: Displays a list of log targets for file systems.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Allow_errors'
      - $ref: '#/components/parameters/Context_names_get'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogTargetsFileSystemsGetResponse'
    post:
      tags:
      - Audit Log Target for File Systems
      summary: Pure Storage POST Log-target-file-systems
      description: Create a new log target for file systems.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Context_names'
      - $ref: '#/components/parameters/Names_required'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogTargetsFileSystemsPost'
        required: false
        x-codegen-request-body-name: log-target-file-system
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogTargetsFileSystemsResponse'
      x-codegen-request-body-name: log-target-file-system
    delete:
      tags:
      - Audit Log Target for File Systems
      summary: Pure Storage DELETE Log-target-file-systems
      description: Delete one or more log targets.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Context_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content: {}
    patch:
      tags:
      - Audit Log Target for File Systems
      summary: Pure Storage PATCH Log-target-file-systems
      description: Modify an existing log target's attributes.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Context_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogTargetsFileSystems'
        required: true
        x-codegen-request-body-name: log-target-file-system
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogTargetsFileSystemsResponse'
      x-codegen-request-body-name: log-target-file-system
components:
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Allow_errors:
      name: allow_errors
      in: query
      description: 'If set to `true`, the API will allow the operation to continue even if there are errors.

        Any errors will be returned in the `errors` field of the response.

        If set to `false`, the operation will fail if there are any errors.

        '
      schema:
        type: boolean
        default: false
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Context_names:
      name: context_names
      in: query
      description: 'Performs the operation on the context specified.


        If specified, the context names must be an array of size 1, and the single element

        must be the name of an array in the same fleet or the name of the fleet itself. If

        not specified, the context will default to the array that received this request.


        Other parameters provided with the request, such as names of volumes or snapshots,

        are resolved relative to the provided `context`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Names_required:
      name: names
      in: query
      description: 'A comma-separated list of resource names.

        '
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Context_names_get:
      name: context_names
      in: query
      description: 'Performs the operation on the unique contexts specified.


        If specified, each context name must be the name of an array in the same fleet or

        the name of the fleet itself.


        If not specified, the context will default to the array that received this request.


        Other parameters provided with the request, such as names of volumes or snapshots,

        are resolved relative to the provided `context`.


        Enter multiple names in comma-separated format.

        For example, `name01,name02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    LogTargetsFileSystemsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/LogTargetsFileSystemsResponse'
    LogTargetsFileSystems:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - type: object
        properties:
          file_system:
            description: The target filesystem where audit logs will be stored.
            title: Reference
            allOf:
            - $ref: '#/components/schemas/_reference'
          keep_for:
            description: 'Specifies the period that audit logs are retained before they are deleted,

              in milliseconds.

              Default value is `null` which means time based retention does not apply.

              Use 0 to reset the value to `null`.

              At least one of the `keep_for` or `keep_size` parameters is required,

              and they can be set together.

              '
            type: integer
            format: int64
            minimum: 86400000
            example: 86400000
          keep_size:
            description: 'Specifies the maximum size of audit logs to be retained.

              Measured in bytes. When exceeded, older logs will be deleted.

              Default value is `null` which means size-based retention does not apply.

              Use 0 to reset the value to `null`.

              At least one of the `keep_for` or `keep_size` parameters is required,

              and they can be set together.

              '
            type: integer
            format: int64
            minimum: 1000000
            example: 1000000
    _resource:
      description: 'An ordinary (as opposed to built-in) resource that can be created, named,

        renamed or deleted by the user. This might be a virtual resource (e.g., a

        file system), or correspond to something in the environment, like a host or a

        server.

        '
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified and cannot refer to another resource.

            '
          type: string
          readOnly: true
        name:
          description: 'A user-specified name.

            The name must be locally unique and can be changed.

            '
          type: string
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name,

            such as volume name, pod name, snapshot name, and so on.

            '
          type: string
        resource_type:
          description: 'Type of the object (full name of the endpoint).

            Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

            `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

            `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

            `policies/snapshot`, etc.

            '
          type: string
          readOnly: true
      x-aliases:
      - _referenceWithFixedType
    LogTargetsFileSystemsPost:
      allOf:
      - $ref: '#/components/schemas/LogTargetsFileSystems'
    LogTargetsFileSystemsResponse:
      type: object
      properties:
        items:
          description: A list of log target objects.
          type: array
          items:
            $ref: '#/components/schemas/LogTargetsFileSystems'
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
