openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Legal Holds API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Legal Holds
  description: Manages the creation, attributes, and deletion of holds on the array. A hold can be also applied to a path under a file system to mark the entries under the path as immutable.
paths:
  /api/2.26/legal-holds:
    get:
      tags:
      - Legal Holds
      summary: Pure Storage List Legal Holds
      description: List legal holds.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsGetResponse'
    post:
      tags:
      - Legal Holds
      summary: Pure Storage Create a Legal Hold
      description: Create a legal hold instance.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names_required'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalHold'
        required: false
        x-codegen-request-body-name: hold
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsResponse'
      x-codegen-request-body-name: hold
    delete:
      tags:
      - Legal Holds
      summary: Pure Storage Delete a Legal Hold
      description: Delete a legal hold instance. Deletion is not allowed if the legal hold is applied to one or more paths.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content: {}
    patch:
      tags:
      - Legal Holds
      summary: Pure Storage Update a Legal Hold
      description: Update a legal hold instance.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalHold'
        required: false
        x-codegen-request-body-name: hold
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsResponse'
      x-codegen-request-body-name: hold
  /api/2.26/legal-holds/held-entities:
    get:
      tags:
      - Legal Holds
      summary: Pure Storage List Held Entities
      description: List entities to which a legal hold has been applied.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/File_system_ids'
      - $ref: '#/components/parameters/File_system_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Paths'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsHeldEntitiesGetResponse'
    post:
      tags:
      - Legal Holds
      summary: Pure Storage Apply This Legal Hold to a New Entity
      description: 'Apply this legal hold to a new entity.

        The `names`, `file_system_names` and `paths` query parameters are required.

        The `recursive` flag is required when applying a hold to a directory.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/File_system_ids'
      - $ref: '#/components/parameters/File_system_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Paths'
      - $ref: '#/components/parameters/Legal_holds_recursive'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsHeldEntitiesResponse'
    patch:
      tags:
      - Legal Holds
      summary: Pure Storage Release This Legal Hold from the Given Entity
      description: 'Release this legal hold from the given entity.

        The `names`, `file_system_names`, `paths` and `released` query parameters are required.

        The `recursive` flag is required when releasing a hold from a directory.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/File_system_ids'
      - $ref: '#/components/parameters/File_system_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Paths'
      - $ref: '#/components/parameters/Legal_holds_recursive'
      - $ref: '#/components/parameters/Legal_holds_release'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalHoldsHeldEntitiesResponse'
components:
  parameters:
    File_system_ids:
      name: file_system_ids
      in: query
      description: 'A comma-separated list of file system IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `file_system_ids`, then an error is returned.

        This cannot be provided together with the `file_system_names` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Legal_holds_recursive:
      name: recursive
      in: query
      description: 'This is a flag to set when recursively applying/releasing legal holds on entities.

        By default, it is set to be false.

        The `recursive` flag is required when applying/releasing a hold to/from a directory.

        '
      schema:
        type: boolean
        default: false
    File_system_names:
      name: file_system_names
      in: query
      description: 'A comma-separated list of file system names.

        If there is not at least one resource that matches

        each of the elements of `file_system_names`, then an error is returned.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Legal_holds_release:
      name: released
      in: query
      description: 'This is a flag to set when releasing an attached legal hold from a path.

        '
      required: true
      schema:
        type: boolean
        default: true
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Names_required:
      name: names
      in: query
      description: 'A comma-separated list of resource names.

        '
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Paths:
      name: paths
      in: query
      description: 'A comma-separated list of paths used for filtering file locks query by paths.

        This may only be specified if `file_system_ids` or `file_system_names` is

        also specified.

        This cannot be provided together with the `inodes` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    LegalHoldsHeldEntitiesResponse:
      type: object
      properties:
        items:
          description: A list of held entities for legal holds.
          type: array
          items:
            $ref: '#/components/schemas/LegalHoldHeldEntity'
    _fixedReferenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    LegalHoldHeldEntity:
      type: object
      properties:
        file_system:
          description: Reference to the file system that the legal hold is applied to.
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
        legal_hold:
          description: Reference to the legal hold.
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
        path:
          description: The path of the file or directory being held.
          type: string
        status:
          description: 'The status of the legal hold with respect to the held entity.

            Valid values include:

            `applied` for holds that are actively applied,

            `applying` for holds that are being recursively applied but have not yet completed,

            `releasing` for holds that are being released recursively but have not yet completed.

            Entities that are releasing will no longer be held once this operation completes.

            '
          type: string
    LegalHoldsHeldEntitiesGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/LegalHoldsHeldEntitiesResponse'
    LegalHoldsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/LegalHoldsResponse'
    LegalHoldsResponse:
      type: object
      properties:
        items:
          description: A list of legal hold instances.
          type: array
          items:
            $ref: '#/components/schemas/LegalHold'
    _realmsReference:
      type: object
      properties:
        realms:
          description: 'Reference to the realms this resource belongs to.

            The value is set to empty array when the resource

            lives outside of a realm.

            '
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/_fixedReference'
    _fixedReference:
      allOf:
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
    LegalHold:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - $ref: '#/components/schemas/_realmsReference'
      - type: object
        properties:
          description:
            description: 'The description of the legal hold instance.

              '
            type: string
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
