openapi: 3.0.1
info:
  title: FlashArray REST Active Directory SMTP API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: SMTP
  description: 'Manages Simple Mail Transfer Protocol (SMTP) settings.

    SMTP allows the array to send email notifications and alerts to recipients.

    '
paths:
  /api/2.52/smtp-servers:
    get:
      tags:
      - SMTP
      summary: Pure Storage List SMTP Server Attributes
      description: Displays SMTP server attributes. Values include `user_name`, `password`, `relay_host`, `sender_domain`, `sender_username`, `subject_prefix`, `body_prefix`, `encryption_mode`, and `name`.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmtpServerGetResponse'
    patch:
      tags:
      - SMTP
      summary: Pure Storage Modify SMTP Server Attributes
      description: Modifies SMTP server attributes. Values include `user_name`, `password`, `relay_host`, `sender_domain`, `sender_username`, `subject_prefix`, `body_prefix`, `encryption_mode`, and `name`.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmtpServer'
        required: true
        x-codegen-request-body-name: smtp
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmtpServerResponse'
      x-codegen-request-body-name: smtp
  /api/2.26/smtp-servers:
    get:
      tags:
      - SMTP
      summary: Pure Storage GET Smtp-servers
      description: List SMTP server attributes for the array network.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset_2'
      - $ref: '#/components/parameters/Sort_2'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmtpServerGetResponse'
    patch:
      tags:
      - SMTP
      summary: Pure Storage PATCH Smtp-servers
      description: Modify SMTP server attributes such as the relay host and sender domain.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmtpServer_2'
        required: true
        x-codegen-request-body-name: smtp
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmtpServerResponse'
      x-codegen-request-body-name: smtp
components:
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset_2:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort_2:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    SmtpServerResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SmtpServer'
    SmtpServerGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SmtpServerResponse'
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    SmtpServer_2:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - type: object
        properties:
          encryption_mode:
            description: 'Enforces an encryption mode when sending alert email messages.

              Valid values include `starttls`.

              Use "" to clear.

              '
            type: string
            example: starttls
          relay_host:
            description: 'Relay server used as a forwarding point for email sent from the array.

              Can be set as a hostname, IPv4 address, or IPv6 address, with optional port numbers.

              The expected format for IPv4 is `ddd.ddd.ddd.ddd:PORT`.

              The expected format for IPv6 is `xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx`, or

              if a port number is specified, `[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:PORT`.

              '
            type: string
          sender_domain:
            description: 'Domain name appended to alert email messages.

              '
            type: string
    _builtInResourceNoId:
      description: 'A built-in resource. Many are singletons predefined by Purity (e.g., support

        settings). Some correspond to a piece of software, like an app, or hardware,

        like a controller. Others are created by the system in response to some event

        (e.g., alerts, audit records).


        Typically, a user can''t create, delete or rename a built-in resource. A few

        can be created or deleted, but not renamed because the names are meaningful

        to Purity (e.g., VIFs, file systems, file system snapshots, volume snapshot).

        '
      type: object
      properties:
        name:
          description: 'A locally unique, system-generated name. The name cannot be modified.

            '
          type: string
          readOnly: true
    SmtpServer:
      allOf:
      - $ref: '#/components/schemas/_builtInResourceNoId'
      - type: object
        properties:
          body_prefix:
            description: 'Optional string added to the beginning of the email body when sending alert email messages.

              HTML tags are not allowed.

              '
            type: string
            maxLength: 256
            example: Classifaction is UNCLASSIFIED
          encryption_mode:
            description: 'Enforces an encryption mode when sending alert email messages.

              Valid values are `starttls`.

              Use "" to clear.

              '
            type: string
            example: starttls
          password:
            description: 'Password for the relay host, if needed.

              '
            type: string
          relay_host:
            description: 'Relay server used as a forwarding point for email sent from the array.

              Can be set as a hostname, IPv4 address, or IPv6 address, with optional port numbers.

              The expected format for IPv4 is `ddd.ddd.ddd.ddd:PORT`.

              The expected format for IPv6 is `xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx` or,

              if a port number is specified, `[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:PORT`.

              '
            type: string
          sender_domain:
            description: 'Domain name appended to alert email messages.

              '
            type: string
          sender_username:
            description: 'The local-part of the email address used when sending alert email messages.

              '
            type: string
          subject_prefix:
            description: 'Optional string added to the beginning of the subject when sending alert email messages.

              HTML tags are not allowed.

              '
            type: string
            maxLength: 64
            example: DC:45 RM:23 RACK:12
          user_name:
            description: 'User name for the relay host, if needed.

              '
            type: string
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
