openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Logs API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Logs
  description: The array collects a log of command activities that can be used for analysis when the logs are sent to Pure Technical Services.
paths:
  /api/2.26/logs:
    get:
      tags:
      - Logs
      summary: Pure Storage GET Logs
      description: Download a history of log events from the array to provide to Pure Technical Services for analysis.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/End_time'
      - $ref: '#/components/parameters/Start_time'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
            text/plain:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
  /api/2.26/logs-async:
    get:
      tags:
      - Logs
      summary: Pure Storage GET Logs-async
      description: List the attributes and status of preparation for a history of log events from the array to provide to Pure Technical Services for analysis.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogsAsyncGetResponse'
    patch:
      tags:
      - Logs
      summary: Pure Storage PATCH Logs-async
      description: Start the preparation for a history of log events from the array to provide to Pure Technical Services for analysis.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogsAsync'
        required: true
        x-codegen-request-body-name: logs-async
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogsAsyncResponse'
      x-codegen-request-body-name: logs-async
  /api/2.26/logs-async/download:
    get:
      tags:
      - Logs
      summary: Pure Storage GET Logs-async/download
      description: Download the files which contain a history of log events from the array to provide to Pure Technical Services for analysis.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
            text/plain:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
components:
  parameters:
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    End_time:
      name: end_time
      in: query
      description: 'When the time window ends (in milliseconds since epoch).

        '
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1514764800000
    Start_time:
      name: start_time
      in: query
      description: 'When the time window starts (in milliseconds since epoch).

        '
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1514764800000
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    _builtInNoId:
      type: object
      properties:
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    LogsAsyncGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/LogsAsyncResponse'
    LogsAsyncResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LogsAsync'
    FileInfo:
      allOf:
      - $ref: '#/components/schemas/_builtInNoId'
      - type: object
        properties:
          length:
            description: 'Length of the file (in bytes).

              '
            type: integer
            readOnly: true
    LogsAsync:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - type: object
        properties:
          available_files:
            description: 'All of the available files ready for download.

              '
            type: array
            readOnly: true
            items:
              $ref: '#/components/schemas/FileInfo'
          end_time:
            description: 'When the time window ends (in milliseconds since epoch).

              start_time and end_time determine the number of hours for which the logs are prepared for.

              At most 6 hours of logs can be prepared in one request.

              start_time and end_time are truncated to hour boundaries.

              '
            type: integer
            format: int64
            minimum: 0
            example: 1514764800000
          hardware_components:
            description: 'All of the hardware components for which logs are being processed.

              '
            type: array
            items:
              $ref: '#/components/schemas/_reference'
          last_request_time:
            description: 'The last time log preparation was requested (in milliseconds since epoch).

              '
            type: integer
            format: int64
            minimum: 0
            readOnly: true
            example: 1514764800000
          processing:
            description: 'Returns a value of `true` if the logs are being prepared.

              '
            type: boolean
            readOnly: true
          progress:
            description: 'A representation of log preparation progress. Ranges from 0 to 1.0.

              '
            type: number
            format: float
            readOnly: true
            example: 0.99
          start_time:
            description: 'When the time window starts (in milliseconds since epoch).

              start_time and end_time determine the number of hours for which the logs are prepared for.

              At most 6 hours of logs can be prepared in one request.

              start_time and end_time are truncated to hour boundaries.

              '
            type: integer
            format: int64
            minimum: 0
            example: 1514764800000
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name,

            such as volume name, pod name, snapshot name, and so on.

            '
          type: string
        resource_type:
          description: 'Type of the object (full name of the endpoint).

            Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

            `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

            `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

            `policies/snapshot`, etc.

            '
          type: string
          readOnly: true
      x-aliases:
      - _referenceWithFixedType
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
