openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Maintenance Windows API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Maintenance Windows
  description: 'During a maintenance window, alerts are suppressed that are related to connections, paths,

    ports, and other resources that are down during maintenance.

    '
paths:
  /api/2.52/maintenance-windows:
    get:
      tags:
      - Maintenance Windows
      summary: Pure Storage List Maintenance Window Details
      description: Displays maintenance window details, including start time, end time, and maintenance type.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceWindowsGetResponse'
    post:
      tags:
      - Maintenance Windows
      summary: Pure Storage Create a Maintenance Window
      description: 'Creates a maintenance window that suppresses alerts for a specified period of time.

        A maintenance window can be manually closed at any time.

        The `names` and `timeout` parameters are required. Set the `names` parameter to `environment`.

        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceWindowPost'
        required: true
        x-codegen-request-body-name: maintenance-window
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceWindowsResponse'
      x-codegen-request-body-name: maintenance-window
    delete:
      tags:
      - Maintenance Windows
      summary: Pure Storage Delete Maintenance Window
      description: 'Deletes an open maintenance window before its scheduled end (`expire`) time.

        The `names` parameter is required and must be set to `environment`.

        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          content: {}
  /api/2.26/maintenance-windows:
    get:
      tags:
      - Maintenance Windows
      summary: Pure Storage List Maintenance Window Details
      description: Displays maintenance window details, including start time, end time, and maintenance type.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset_2'
      - $ref: '#/components/parameters/Sort_2'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceWindowsGetResponse'
    post:
      tags:
      - Maintenance Windows
      summary: Pure Storage Create a Maintenance Window
      description: 'Creates a maintenance window that suppresses alerts for a specified period of time.

        A maintenance window can be manually closed at any time.

        The `names` and `timeout` parameters are required. Set the `names` parameter to `array`.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names_required'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceWindowPost_2'
        required: true
        x-codegen-request-body-name: maintenance-window
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceWindowsResponse'
      x-codegen-request-body-name: maintenance-window
    delete:
      tags:
      - Maintenance Windows
      summary: Pure Storage Delete Maintenance Window
      description: 'Deletes an active maintenance window before its scheduled end (`expire`) time.

        The `names` parameter is required and must be set to `array`.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content: {}
components:
  schemas:
    MaintenanceWindowsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/MaintenanceWindowsResponse'
    MaintenanceWindowPost_2:
      type: object
      properties:
        timeout:
          description: 'Duration of a maintenance window measured in milliseconds.

            The `names` and `timeout` parameters must be set together, and the `names` parameter

            must be set to `array`.

            '
          type: integer
          format: int32
          example: 14400000
    MaintenanceWindow:
      allOf:
      - $ref: '#/components/schemas/_resourceNoId'
      - description: 'The period of time during which maintenance will occur.

          Alerts are suppressed during the maintenance window.

          '
        type: object
        properties:
          created:
            description: 'The maintenance window start time, measured in milliseconds since the UNIX epoch.

              '
            type: integer
            format: int64
            readOnly: true
          expires:
            description: 'The maintenance window end time, measured in milliseconds since the UNIX epoch.

              '
            type: integer
            format: int64
            readOnly: true
    _resourceNoId:
      description: 'An ordinary (as opposed to built-in) resource that can be created, named,

        renamed or deleted by the user. This might be a virtual resource (e.g., a

        volume), or correspond to something in the environment, like a host or a

        server.

        '
      type: object
      properties:
        name:
          description: 'A user-specified name.

            The name must be locally unique and can be changed.

            '
          type: string
    MaintenanceWindowPost:
      type: object
      properties:
        timeout:
          description: 'The specified length of time that alerts are suppressed during a maintenance window,

            measured in milliseconds.

            The maintenance window timeout value must be between `60000` (1 minute)

            and `86400000` (24 hours).

            The value entered is rounded down to the nearest minute.

            The `names` and `timeout` parameters must be set together, and the `names` parameter

            must be set to `environment`.

            '
          type: integer
          format: int32
          example: 3600000
          x-minimum: 0
          x-maximum: 86400000
    MaintenanceWindowsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MaintenanceWindow'
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset_2:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Names_required:
      name: names
      in: query
      description: 'A comma-separated list of resource names.

        '
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort_2:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
