openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Invoices API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Invoices
  description: 'Provides information about Pure1 subscription invoices.

    '
paths:
  /api/1.5/invoices:
    get:
      tags:
      - Invoices
      summary: Pure Storage Get Invoices
      description: 'Retrieves information about Pure1 subscription invoices.

        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Partner_purchase_orders'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Subscription_ids'
      - $ref: '#/components/parameters/Subscription_names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
            X-RateLimit-Remaining-second:
              description: 'The number of requests remaining for the organization in that second.

                '
              schema:
                type: integer
            X-RateLimit-Remaining-minute:
              description: 'The number of requests remaining for the organization in that minute.

                '
              schema:
                type: integer
            X-RateLimit-Limit-second:
              description: The number of requests available per second.
              schema:
                type: integer
            X-RateLimit-Limit-minute:
              description: The number of requests available per minute.
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceGetResponse'
        '400':
          $ref: '#/components/responses/Error400'
        '403':
          $ref: '#/components/responses/Error403'
        '404':
          $ref: '#/components/responses/Error404'
        '429':
          $ref: '#/components/responses/Error429'
        '500':
          $ref: '#/components/responses/Error500'
components:
  responses:
    Error404:
      description: NOT FOUND
      headers:
        X-Request-ID:
          description: Supplied by client during request or generated by server.
          schema:
            type: object
        X-RateLimit-Remaining-minute:
          description: 'The number of requests remaining for the organization in that minute.

            '
          schema:
            type: object
        X-RateLimit-Remaining-second:
          description: 'The number of requests remaining for the organization in that second.

            '
          schema:
            type: object
        X-RateLimit-Limit-minute:
          description: The number of requests available per minute.
          schema:
            type: object
        X-RateLimit-Limit-second:
          description: The number of requests available per second.
          schema:
            type: object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error500:
      description: INTERNAL SERVER ERROR
      headers:
        X-Request-ID:
          description: Supplied by client during request or generated by server.
          schema:
            type: object
        X-RateLimit-Remaining-minute:
          description: 'The number of requests remaining for the organization in that minute.

            '
          schema:
            type: object
        X-RateLimit-Remaining-second:
          description: 'The number of requests remaining for the organization in that second.

            '
          schema:
            type: object
        X-RateLimit-Limit-minute:
          description: The number of requests available per minute.
          schema:
            type: object
        X-RateLimit-Limit-second:
          description: The number of requests available per second.
          schema:
            type: object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error403:
      description: FORBIDDEN
      headers:
        X-Request-ID:
          description: Supplied by client during request or generated by server.
          schema:
            type: object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorNoContext'
    Error400:
      description: BAD REQUEST
      headers:
        X-Request-ID:
          description: Supplied by client during request or generated by server.
          schema:
            type: object
        X-RateLimit-Remaining-minute:
          description: 'The number of requests remaining for the organization in that minute.

            '
          schema:
            type: object
        X-RateLimit-Remaining-second:
          description: 'The number of requests remaining for the organization in that second.

            '
          schema:
            type: object
        X-RateLimit-Limit-minute:
          description: The number of requests available per minute.
          schema:
            type: object
        X-RateLimit-Limit-second:
          description: The number of requests available per second.
          schema:
            type: object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error429:
      description: TOO MANY REQUESTS
      headers:
        X-Request-ID:
          description: Supplied by client during request or generated by server.
          schema:
            type: object
        X-RateLimit-Remaining-minute:
          description: 'The number of requests remaining for the organization in that minute.

            '
          schema:
            type: object
        X-RateLimit-Remaining-second:
          description: 'The number of requests remaining for the organization in that second.

            '
          schema:
            type: object
        X-RateLimit-Limit-minute:
          description: The number of requests available per minute.
          schema:
            type: object
        X-RateLimit-Limit-second:
          description: The number of requests available per second.
          schema:
            type: object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorNoContext'
  schemas:
    _tax:
      type: object
      properties:
        amount:
          description: The total taxes of current invoice item, currency is specified in invoice currency.
          type: number
          format: double
          example: 70.0
        exemption_statement:
          description: The tax exemption statement.
          type: string
        percentage:
          description: The tax ratio in percentage.
          type: number
          format: float
          minimum: 0
          maximum: 1
          example: 0.07
    InvoiceLineComponent:
      type: object
      properties:
        description:
          type: string
          example: 24/7 support
        item:
          description: The name of invoice component.
          type: string
          example: 08-0144
        quantity:
          description: The quantity of current invoice component.
          type: integer
          format: int64
          minimum: 0
          example: 1
    Error:
      type: object
      properties:
        errors:
          description: The list of errors encountered.
          type: array
          items:
            $ref: '#/components/schemas/_errorErrors'
    ErrorNoContext:
      type: object
      properties:
        message:
          type: string
          example: Something was wrong
    _errorErrors:
      type: object
      properties:
        context:
          type: string
          example: Error with ...
        message:
          type: string
          example: Something was wrong
    InvoiceResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Invoice'
    InvoiceGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/InvoiceResponse'
    Invoice:
      type: object
      properties:
        amount:
          description: The total invoice amount, expressed in the currency defined in `currency`.
          type: number
          format: double
          example: 1070.0
        currency:
          description: 'The currency of the invoice in ISO 4217 format.

            This currency applies to the total invoice amount as well as all amounts in line items.

            '
          type: string
          example: USD
        date:
          description: 'The issuance date.

            Represented as a timestamp of 00:00 on that date in UTC, in milliseconds since UNIX epoch.

            '
          type: integer
          format: int64
          example: 1672531200000
        due_date:
          description: 'The payment due date.

            Represented as a timestamp of 00:00 on that date in UTC, in milliseconds since UNIX epoch.

            '
          type: integer
          format: int64
          example: 1672531200000
        end_user_name:
          description: The end user customer name.
          type: string
          example: Pure Storage
        end_user_purchase_order:
          description: The end user customer purchase order number.
          type: string
          example: 415Tib/400Tib/123456
        id:
          description: The invoice number, a globally unique identifier for this invoice.
          type: string
          example: INV123456
        lines:
          description: A list of invoice line items.
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLine'
        partner_purchase_order:
          description: The partner purchase order number.
          type: string
          example: 123456-1
        payment_terms:
          description: The invoice payment terms.
          type: string
          example: Net 45
        sales_representative:
          description: The sales representative that issued the invoice.
          type: string
          example: John Doe
        ship_date:
          description: 'The invoice shipment date.

            Represented as a timestamp of 00:00 on that date in UTC, in milliseconds since UNIX epoch.

            '
          type: integer
          format: int64
          example: 1672531200000
        status:
          description: The invoice status. Values include `open` and `paid`.
          type: string
          example: open
        subscription:
          description: A reference to which subscription this invoice belongs.
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
    InvoiceLine:
      type: object
      properties:
        amount:
          description: The total price of current invoice item, currency is specified in invoice currency.
          type: number
          format: double
          example: 1000.0
        components:
          description: The sub-components of current invoice item.
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLineComponent'
        description:
          type: string
          example: SS-DFM-15TB 1 Month Evergreen Forever Subscription, NBD Delivery, 24/7 Support
        end_date:
          description: 'The invoice item end date.

            Represented as a timestamp of 00:00 on that date in UTC, in milliseconds since UNIX epoch.

            '
          type: integer
          format: int64
          example: 1672531200000
        item:
          description: The name of invoice item.
          type: string
          example: SS-DFM-15TB 1MO,ADV,GOLD
        quantity:
          description: The quantity of current invoice item.
          type: integer
          format: int64
          minimum: 0
          example: 2
        start_date:
          description: 'The invoice item start date.

            Represented as a timestamp of 00:00 on that date in UTC, in milliseconds since UNIX epoch.

            '
          type: integer
          format: int64
          example: 1672531200000
        tax:
          $ref: '#/components/schemas/_tax'
        unit_price:
          description: The unit price of current invoice item, currency is specified in invoice currency.
          type: number
          format: double
          example: 500.0
    _fixedReference:
      type: object
      properties:
        id:
          description: The opaque and unique id of this resource.
          type: string
          readOnly: true
          example: 2a989a09-c851-4d52-9ec6-ab728b1c04db
        name:
          description: The name of this resource.
          type: string
          readOnly: true
          example: example_name
        resource_type:
          description: 'The type of this resource represented by the name of its REST endpoint.

            For example, "arrays", "network-interfaces", and "metrics".

            The value may be `null` if the resource is not represented.

            '
          type: string
          readOnly: true
          example: example_resource_type
      x-readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the continuation_token

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
          example: MThkMzJmYWUtZDI3OS00ODEzLWIzODYtMmM3NmFhMTMwM2My
        total_item_count:
          description: Total number of items after applying filter params.
          type: integer
          format: int32
          example: 1
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
    Filter:
      name: filter
      in: query
      description: 'Exclude resources that don''t match the specified criteria.

        Single quotes are required around all strings inside the filters.

        '
      schema:
        type: string
    Subscription_names:
      name: subscription_names
      in: query
      description: 'A comma-separated list of subscription names.

        If there is not at least one resource that matches each `subscription.name`

        element, an error is returned.

        Single quotes are required around all strings.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
        x-quoted: true
      x-quoted: true
    Continuation_token:
      name: continuation_token
      in: query
      description: 'An opaque token used to iterate over a collection.

        The token to use on the next request is returned in the

        `continuation_token` field of the result.

        Single quotes are required around all strings.

        '
      schema:
        type: string
        x-quoted: true
      x-quoted: true
    Partner_purchase_orders:
      name: partner_purchase_orders
      in: query
      description: 'A comma-separated list of partner purchase order numbers.

        If there is not at least one resource that matches each `partner_purchase_order` element,

        an error is returned.

        Single quotes are required around all strings.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
        x-quoted: true
      x-quoted: true
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limit the size of the response to the specified number of resources.

        A limit of 0 can be used to get the number of resources without getting

        all of the resources. It will be returned in the total_item_count field.

        If a client asks for a page size larger than the maximum number, the request

        is still valid. In that case the server just returns the maximum number of

        items, disregarding the client''s page size request. If not specified, defaults

        to 1000.

        '
      schema:
        type: integer
        format: int32
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API endpoint (except `/oauth2`)

        '
      schema:
        type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If there is not at least one resource that matches each `id` element,

        an error is returned.

        Single quotes are required around all strings.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
        x-quoted: true
      x-quoted: true
    Subscription_ids:
      name: subscription_ids
      in: query
      description: 'A comma-separated list of subscription IDs.

        If there is not at least one resource that matches each `subscription.id`

        element, an error is returned.

        Single quotes are required around all strings.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
        x-quoted: true
      x-quoted: true
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        If you provide a sort you will not get a continuation token in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
