openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Remote Arrays API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Remote Arrays
  description: 'Remote arrays provide the ability to list and manage all the remote arrays known to an array.

    '
paths:
  /api/2.52/remote-arrays:
    get:
      tags:
      - Remote Arrays
      summary: Pure Storage List Remote Arrays
      description: 'Dispalys arrays in the current fleet, as well as arrays that the current array has existing

        replication connections to.


        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - name: current_fleet_only
        in: query
        description: 'If current_fleet_only is specified, then results will only show arrays from the same fleet to

          which the current array is a member of.

          '
        schema:
          type: boolean
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteArraysResponse'
  /api/2.26/remote-arrays:
    get:
      tags:
      - Remote Arrays
      summary: Pure Storage List Remote Arrays
      description: 'Lists arrays in the current fleet, as well as arrays that the current array has existing

        replication connections to.


        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - name: current_fleet_only
        in: query
        description: 'If current_fleet_only is specified, then results will only show arrays from the same fleet to

          which the current array is a member of.

          '
        schema:
          type: boolean
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids_2'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset_2'
      - $ref: '#/components/parameters/Sort_2'
      - $ref: '#/components/parameters/Total_only'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteArraysResponse'
    patch:
      tags:
      - Remote Arrays
      summary: Pure Storage Modify Remote Arrays
      description: Modifies the topology group of remote arrays.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids_2'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/To_topology_group_ids'
      - $ref: '#/components/parameters/To_topology_group_names'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteArrayResponse'
components:
  schemas:
    _referenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name, such as volume name, pod name,

            snapshot name, and so on.

            '
          type: string
    _remoteArrayFleet:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - type: object
        properties:
          is_local:
            description: 'If set to `true`, the current array is a member of the fleet.

              '
            type: boolean
            example: false
    _referenceWithoutTypeWithIsLocal:
      allOf:
      - $ref: '#/components/schemas/_referenceWithoutType'
      - type: object
        properties:
          is_local:
            description: 'If set to `true`, the location reference is to the local array.

              If set to `false`, the location reference is to a remote location,

              such as a remote array or offload target.

              '
            type: boolean
            readOnly: true
    _resource:
      description: 'An ordinary (as opposed to built-in) resource that can be created, named,

        renamed or deleted by the user. This might be a virtual resource (e.g., a

        file system), or correspond to something in the environment, like a host or a

        server.

        '
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified and cannot refer to another resource.

            '
          type: string
          readOnly: true
        name:
          description: 'A user-specified name.

            The name must be locally unique and can be changed.

            '
          type: string
    _fixedReferenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
    RemoteArrayResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RemoteArray_2'
    _referenceWritable:
      allOf:
      - $ref: '#/components/schemas/_referenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

              `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

              `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, `policies/snapshot`, etc.

              '
            type: string
      x-aliases:
      - _reference
    _api_versions:
      description: A list of supported API versions.
      type: array
      items:
        type: string
      example:
      - '1.0'
      - '1.1'
      - '1.2'
      - '1.3'
      - '1.4'
      - '1.5'
      - '1.6'
      - '1.7'
      - '1.8'
      - '1.9'
      - '1.10'
      - '1.11'
      - '1.12'
      - '1.13'
      - '1.14'
      - '1.15'
      - '1.16'
      - '1.17'
      - '2.0'
    _fixedReferenceWithIsLocal:
      allOf:
      - $ref: '#/components/schemas/_fixedReference'
      - $ref: '#/components/schemas/_referenceWithoutTypeWithIsLocal'
      - type: object
        properties:
          resource_type:
            description: "Type of the object (full name of the endpoint).\n  Valid values are the unique part of the resource's REST endpoint.\n  For example, a reference to a fleet would have a\n  `resource_type` of `fleets`.\n"
            type: string
    RemoteArraysResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - type: object
        properties:
          items:
            description: 'Returns a list of all items after filtering.

              The values are displayed for each name where meaningful.

              '
            type: array
            items:
              $ref: '#/components/schemas/RemoteArray'
    RemoteArray_2:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - type: object
        properties:
          api_versions:
            $ref: '#/components/schemas/_api_versions'
          fleet:
            $ref: '#/components/schemas/_fixedReferenceWithIsLocal'
          is_local:
            description: If set to `true`, this array is the current array.
            type: boolean
            example: false
          model:
            description: Specifies the array model.
            type: string
            example: FlashBlade//S200
          os:
            description: 'Specifies the operating system. Valid values are `Purity`, `Purity//FA`, and `Purity//FB`.

              '
            type: string
            example: Purity//FA
          topology_group:
            description: The topology group in which this array is a member.
            title: ReferenceWritable
            allOf:
            - $ref: '#/components/schemas/_referenceWritable'
          version:
            description: Specifies the operating system version.
            type: string
            example: 4.4.99
    RemoteArray:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - type: object
        properties:
          api_versions:
            $ref: '#/components/schemas/_api_versions'
          fleet:
            $ref: '#/components/schemas/_remoteArrayFleet'
          is_local:
            description: 'If set to `true`, this array is the current array.

              '
            type: boolean
            example: false
          model:
            description: 'Specifies the array model.

              '
            type: string
            example: FA//X
          os:
            description: 'Specifies the operating system. Valid values are `Purity`, `Purity//FA`, and `Purity//FB`.

              '
            type: string
            example: Purity//FA
          version:
            description: 'Specifies the operating system version.

              '
            type: string
            example: 6.8.0
    _fixedReference:
      allOf:
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
  parameters:
    Total_only:
      name: total_only
      in: query
      description: 'If set to `true`, returns the aggregate value of all items after filtering.

        Where it makes more sense, the average value is displayed instead.

        The values are displayed for each name where meaningful.

        If `total_only=true`, the `items` list will be empty.

        '
      schema:
        type: boolean
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset_2:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    To_topology_group_ids:
      name: to_topology_group_ids
      in: query
      description: 'Moves selected remote array to the specified topology group by ID.

        One of the `to_topology_group_ids` or `to_topology_group_names` parameters is required,

        but they cannot be set together.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort_2:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    Ids:
      name: ids
      in: query
      description: "A comma-separated list of unique resource IDs. At least one resource must match\n each specified ID, otherwise an error is returned. This parameter is required\n  if ids or names is not provided, but it cannot be used together with name or names.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Ids_2:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    To_topology_group_names:
      name: to_topology_group_names
      in: query
      description: 'Moves selected remote array to the specified topology group by name.

        One of the `to_topology_group_ids` or `to_topology_group_names` parameters is required,

        but they cannot be set together.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
