openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Nodes API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Nodes
  description: Manages the nodes for pNFS. These nodes are where the client will read/write to when pNFS is enabled.
paths:
  /api/2.26/nodes:
    get:
      tags:
      - Nodes
      summary: Pure Storage GET Nodes
      description: List one or more nodes.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_only'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeGetResponse'
    patch:
      tags:
      - Nodes
      summary: Pure Storage PATCH Nodes
      description: Modify a node's attributes including its management address and serial number.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
        required: false
        x-codegen-request-body-name: node
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeResponse'
      x-codegen-request-body-name: node
  /api/2.26/nodes/batch:
    post:
      tags:
      - Nodes
      summary: Pure Storage POST Nodes/batch
      description: Add one or more nodes.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Add_to_groups'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Node'
        required: true
        x-codegen-request-body-name: items
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeResponse'
      x-codegen-request-body-name: items
components:
  parameters:
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Total_only:
      name: total_only
      in: query
      description: 'If set to `true`, returns the aggregate value of all items after filtering.

        Where it makes more sense, the average value is displayed instead.

        The values are displayed for each name where meaningful.

        If `total_only=true`, the `items` list will be empty.

        '
      schema:
        type: boolean
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Add_to_groups:
      name: add_to_groups
      in: query
      description: 'If `true`, the node being added will automatically be added

        to all node groups that other members of its resiliency

        group already belong to. This parameter must be set to `true`

        when adding any node that will be part of a resiliency group.

        '
      schema:
        type: boolean
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    NodeGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/NodeResponse'
      - type: object
        properties:
          total:
            $ref: '#/components/schemas/Node'
    NodeResponse:
      type: object
      properties:
        items:
          description: A list of node objects.
          type: array
          items:
            $ref: '#/components/schemas/Node'
    Node:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - type: object
        properties:
          capacity:
            description: 'The available capacity of the node in bytes.

              '
            type: integer
            format: int64
            readOnly: true
          chassis_serial_number:
            description: 'The serial number of the chassis the node is in, if applicable.

              '
            type: string
            readOnly: true
          data_addresses:
            description: 'List of data IP addresses of the node.

              '
            type: array
            readOnly: true
            items:
              type: string
          details:
            description: 'The description of the status of the node if not healthy.

              '
            type: string
            readOnly: true
          management_address:
            description: 'The control IP address of the node. A connection will be made

              to this address to get info on the node such as the data addresses.

              If a connection cannot be made to the given management address,

              both the POST and PATCH request modifying this field will fail.

              '
            type: string
          raw_capacity:
            description: 'The raw capacity of the node in bytes.

              '
            type: integer
            format: int64
            readOnly: true
          serial_number:
            description: 'The serial number of the node.

              If the given serial number does not match the serial number of the node,

              both the POST and PATCH request modifying this field will fail.

              '
            type: string
          status:
            description: 'The status of the node.

              Values include `critical`, `healthy`, and `unhealthy`.

              '
            type: string
            readOnly: true
          unique:
            description: 'The unique physical space occupied by customer data in bytes.

              '
            type: integer
            format: int64
            readOnly: true
    _resource:
      description: 'An ordinary (as opposed to built-in) resource that can be created, named,

        renamed or deleted by the user. This might be a virtual resource (e.g., a

        file system), or correspond to something in the environment, like a host or a

        server.

        '
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified and cannot refer to another resource.

            '
          type: string
          readOnly: true
        name:
          description: 'A user-specified name.

            The name must be locally unique and can be changed.

            '
          type: string
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
