openapi: 3.0.1
info:
  title: FlashArray REST Active Directory RDL API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: RDL
  description: Displays Rapid Data Locking (RDL) configuration and performs functionality tests of the associated Enterprise Key Management (EKM) servers.
paths:
  /api/2.26/rapid-data-locking:
    get:
      tags:
      - RDL
      summary: Pure Storage Get the Status of the Rapid Data Locking Feature.
      description: 'Displays the status of the Rapid Data Locking feature.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RapidDataLockingResponse'
    patch:
      tags:
      - RDL
      summary: Pure Storage Modifies the Rapid Data Locking Feature.
      description: 'Modifies the Rapid Data Locking feature. Note that the feature can only

        be enabled if there are no file systems nor buckets created on the array.

        Once enabled, the feature cannot be modified.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RapidDataLocking'
        required: true
        x-codegen-request-body-name: rapid-data-locking
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RapidDataLockingResponse'
      x-codegen-request-body-name: rapid-data-locking
  /api/2.26/rapid-data-locking/test:
    get:
      tags:
      - RDL
      summary: Pure Storage Displays Rapid Data Locking Test Results.
      description: 'Displays a detailed result of a Rapid Data Locking test.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResultResponse'
  /api/2.26/rapid-data-locking/rotate:
    post:
      tags:
      - RDL
      summary: Pure Storage Rotates the External Keys on the Associated EKM Appliance.
      description: 'Rotates the external keys on the associated EKM appliance.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content: {}
components:
  schemas:
    _fixedReferenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
    RapidDataLockingResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RapidDataLocking'
    RapidDataLocking:
      type: object
      properties:
        enabled:
          description: '`True` if the Rapid Data Locking feature is enabled.

            '
          type: boolean
          example: true
        kmip_server:
          description: 'The KMIP server configuration associated with RDL.

            '
          title: Reference
          allOf:
          - $ref: '#/components/schemas/_reference'
    _fixedReference:
      allOf:
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
    TestResult:
      type: object
      properties:
        component_address:
          description: Address of the component running the test.
          type: string
          example: 10.230.94.21
        component_name:
          description: Name of the component running the test.
          type: string
          example: fm1
        description:
          description: What the test is doing.
          type: string
          example: Testing phonehome connectivity
        destination:
          description: The URI of the target server being tested.
          type: string
          example: ra.cloud-support.purestorage.com
        enabled:
          description: Is the service enabled or not?
          type: boolean
          example: true
        resource:
          description: A reference to the object being tested.
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
        result_details:
          description: Additional information about the test result.
          type: string
          example: Timeout connecting to phonehome endpoint
        success:
          description: 'Returns a value of `true` if the specified test succeeded.

            Returns a value of `false` if the specified test failed.

            '
          type: boolean
        test_type:
          description: 'Displays the type of test being performed. The returned values are determined

            by the `resource` being tested and its configuration.

            '
          type: string
          example: phonehome
    TestResultResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TestResult'
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name,

            such as volume name, pod name, snapshot name, and so on.

            '
          type: string
        resource_type:
          description: 'Type of the object (full name of the endpoint).

            Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

            `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

            `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

            `policies/snapshot`, etc.

            '
          type: string
          readOnly: true
      x-aliases:
      - _referenceWithFixedType
  parameters:
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
