openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Apps API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Apps
  description: 'Apps that extend array functionality can be integrated into the Purity//FA operating system.

    '
paths:
  /api/2.52/apps:
    get:
      tags:
      - Apps
      summary: Pure Storage List Apps
      description: Displays a list of installed apps.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppGetResponse'
    patch:
      tags:
      - Apps
      summary: Pure Storage Modify App
      description: 'Modifies an installed app or modifies Virtual Network Computing (VNC) access for apps that are

        being patched.

        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Names_required'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
        required: true
        x-codegen-request-body-name: app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppResponse'
      x-codegen-request-body-name: app
  /api/2.52/apps/nodes:
    get:
      tags:
      - Apps
      summary: Pure Storage List App Nodes
      description: Displays a list of installed apps and their nodes.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/App_names'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppNodeGetResponse'
components:
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Names_required:
      name: names
      in: query
      description: 'Performs the operation on the unique name specified.

        For example, `name01`.

        Enter multiple names in comma-separated format.

        '
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    App_names:
      name: app_names
      in: query
      description: 'The name of the installed app.

        Enter multiple names in comma-separated format.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    AppNodeGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/AppNodeResponse'
    AppResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/App'
    AppNode:
      description: 'An individual node of a Purity app. Nodes are indexed starting at `0`.

        '
      type: object
      properties:
        app:
          description: A reference to the app of which this node is a part.
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
        index:
          description: An index that represents this node.
          type: integer
          readOnly: true
          example: 0
        status:
          description: 'The node status. Possible values are `starting`, `healthy`, `unhealthy`, `critical`,

            `stopping`, and `disabled`.

            '
          type: string
          readOnly: true
          example: healthy
        version:
          description: The node version.
          type: string
          readOnly: true
          example: 1.0.0
        vnc:
          description: 'The VNC information used to access this node if VNC is enabled.

            '
          type: array
          readOnly: true
          items:
            type: string
            example: 10.1.1.10:5900
      x-readOnly: true
    App:
      allOf:
      - $ref: '#/components/schemas/_builtInResourceNoId'
      - description: 'An app that is installed on Purity to extend its functionality.

          The app is an add-on service that is integrated into the system to extend array functionality.

          '
        type: object
        properties:
          description:
            description: 'A description of the app.

              '
            type: string
            readOnly: true
            example: Snapshot offload to NFS or Amazon S3
          details:
            description: 'Details of the status of the app.

              '
            type: string
            readOnly: true
            example: Insufficient resources to operate
          enabled:
            description: 'If set to `true`, the app is enabled. By default, apps are disabled.

              '
            type: boolean
          status:
            description: 'The status of the app. Values include `healthy` and `unhealthy`.

              For cluster apps, this represents the aggregate status of the app.

              The aggregate status is only `healthy` if all nodes are `healthy`&#59;

              otherwise, it is `unhealthy`.

              '
            type: string
            readOnly: true
            example: healthy
          version:
            description: 'The app version.

              For cluster apps, this represents the node version if all nodes are of the same version.

              If the node versions differ, a value of `null` is returned.

              '
            type: string
            readOnly: true
            example: 1.0.0
          vnc_enabled:
            description: 'If set to `true`, VNC access is enabled. By default, VNC access is disabled.

              '
            type: boolean
    AppGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/AppResponse'
    AppNodeResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AppNode'
    _fixedReference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
      x-aliases:
      - _fixedReferenceWithoutType
    _builtInResourceNoId:
      description: 'A built-in resource. Many are singletons predefined by Purity (e.g., support

        settings). Some correspond to a piece of software, like an app, or hardware,

        like a controller. Others are created by the system in response to some event

        (e.g., alerts, audit records).


        Typically, a user can''t create, delete or rename a built-in resource. A few

        can be created or deleted, but not renamed because the names are meaningful

        to Purity (e.g., VIFs, file systems, file system snapshots, volume snapshot).

        '
      type: object
      properties:
        name:
          description: 'A locally unique, system-generated name. The name cannot be modified.

            '
          type: string
          readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
