openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Directory Quotas API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Directory Quotas
  description: 'Directory quotas provide the ability to set capacity limits on managed directories.

    '
paths:
  /api/2.52/directory-quotas:
    get:
      tags:
      - Directory Quotas
      summary: Pure Storage List Directories with Attached Quota Policies
      description: Displays a list of directories and the quota policies attached to them. Directories with multiple policies are listed repeatedly (once per policy). The directories without a policy attached are not listed.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Allow_errors'
      - $ref: '#/components/parameters/Context_names_get'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Directory_ids'
      - $ref: '#/components/parameters/Directory_names'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Policy_ids'
      - $ref: '#/components/parameters/Policy_names'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectoryQuotasGetResponse'
        '207':
          description: 'Partial success. Some resources were returned, but there

            were also errors possibly preventing some resources from

            being returned.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectoryQuotasGetResponse'
components:
  parameters:
    Directory_names:
      name: directory_names
      in: query
      description: 'Performs the operation on the managed directory names specified.

        Enter multiple full managed directory names in comma-separated format.

        For example, `fs:dir01,fs:dir02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Allow_errors:
      name: allow_errors
      in: query
      description: 'If set to `true`, the API will allow the operation to continue even if there are errors.

        Any errors will be returned in the `errors` field of the response.

        If set to `false`, the operation will fail if there are any errors.

        '
      schema:
        type: boolean
        default: false
    Policy_ids:
      name: policy_ids
      in: query
      description: 'Performs the operation on the unique policy IDs specified.

        Enter multiple policy IDs in comma-separated format.

        The `policy_ids` or `policy_names` parameter is required, but they cannot be set together.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Policy_names:
      name: policy_names
      in: query
      description: 'Performs the operation on the policy names specified.

        Enter multiple policy names in comma-separated format.

        For example, `name01,name02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Directory_ids:
      name: directory_ids
      in: query
      description: 'Performs the operation on the unique managed directory IDs specified.

        Enter multiple managed directory IDs in comma-separated format.

        The `directory_ids` or `directory_names` parameter is required, but they cannot be set together.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Context_names_get:
      name: context_names
      in: query
      description: 'Performs the operation on the unique contexts specified.


        If specified, each context name must be the name of an array in the same fleet or

        the name of the fleet itself.


        If not specified, the context will default to the array that received this request.


        Other parameters provided with the request, such as names of volumes or snapshots,

        are resolved relative to the provided `context`.


        Enter multiple names in comma-separated format.

        For example, `name01,name02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    _errorContextResponse:
      type: object
      properties:
        errors:
          description: The list of errors encountered when attempting to perform an operation.
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/_errorcontextresponseErrors'
    DirectoryQuotasGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/DirectoryQuotasResponse'
      - $ref: '#/components/schemas/_errorContextResponse'
    _errorcontextresponseErrors:
      type: object
      properties:
        context:
          description: 'Contains information relating to the cause of this error,

            or the name of the object that was being processed when the error was encountered.

            This may be `null` for more general errors.

            '
          type: string
        location_context:
          description: 'Contains information relating to the context in which the request was executing

            when the error occurred.

            For example, this may be the name of an array in the same fleet.

            This may be `null` for more general errors, or if no explicit `context` parameter

            was provided with the request.

            '
          title: FixedReferenceWithType
          allOf:
          - $ref: '#/components/schemas/_fixedReferenceWithType'
        message:
          description: A description of the error which occurred.
          type: string
          example: Resource does not exist.
      x-aliases:
      - _errorContextResponseErrors
    _fixedReferenceWithType:
      allOf:
      - $ref: '#/components/schemas/_fixedReference'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
      x-aliases:
      - _fixedReference
    _context:
      type: object
      properties:
        context:
          description: 'The context in which the operation was performed.


            Valid values include a reference to any array which is a member of the same fleet

            or to the fleet itself.


            Other parameters provided with the request, such as names of volumes or snapshots,

            are resolved relative to the provided `context`.

            '
          readOnly: true
          title: FixedReferenceWithType
          allOf:
          - $ref: '#/components/schemas/_fixedReferenceWithType'
    DirectoryQuotasResponse:
      type: object
      properties:
        items:
          description: 'Displays a list of all items after filtering.

            The values are displayed for each name, if meaningful.

            '
          type: array
          items:
            $ref: '#/components/schemas/DirectoryQuota'
    _fixedReference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
      x-aliases:
      - _fixedReferenceWithoutType
    DirectoryQuota:
      allOf:
      - $ref: '#/components/schemas/_context'
      - type: object
        properties:
          directory:
            description: The directory to which the quota applies.
            title: FixedReferenceWithType
            allOf:
            - $ref: '#/components/schemas/_fixedReferenceWithType'
          enabled:
            description: 'Returns a value of `true` if the policy is enabled.

              '
            type: boolean
            readOnly: true
          enforced:
            description: 'Defines whether the quota rule is enforced or unenforced.

              If the quota rule is enforced and logical space usage exceeds the quota limit,

              any modification operations that result in a need for more space are blocked.

              If the quota rule is unenforced and logical space usage exceeds the quota limit, notification

              emails are sent to targets that are specified using the `notification` parameter.

              No client operations are blocked when an unenforced limit is exceeded.

              If set to `true`, the limit is enforced. If set to `false`, notification targets are informed

              when the usage exceeds 80 percent of the limit.

              '
            type: boolean
          path:
            description: 'Absolute path of the directory in the file system.

              '
            type: string
            readOnly: true
          percentage_used:
            description: 'The percentage of the space used in the directory with respect to the quota limit.

              '
            type: number
            format: float
            minimum: 0
            readOnly: true
          policy:
            description: 'The effective quota policy that imposes the limit. This is the policy with the lowest limit.

              '
            title: FixedReferenceWithType
            allOf:
            - $ref: '#/components/schemas/_fixedReferenceWithType'
          quota_limit:
            description: 'Effective quota limit imposed by the quota policy rule attached to the directory, measured in

              bytes.

              '
            type: integer
            format: int64
            minimum: 0
            readOnly: true
          rule_name:
            description: 'Name of the rule that results in this quota and behavior being applied to this directory.

              '
            type: string
            readOnly: true
          usage:
            description: 'The amount of logically written data for the directory, measured in bytes.

              '
            type: integer
            format: int64
            minimum: 0
            readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
