openapi: 3.0.1
info:
  title: FlashArray REST Active Directory File System Junctions API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: File System Junctions
  description: Manages the creation, and deletion of file system junctions. Junctions link a specific path in the origin file system to the root of a destination file system.
paths:
  /api/2.26/file-system-junctions:
    get:
      tags:
      - File System Junctions
      summary: Pure Storage GET File-system-junctions
      description: List file system junctions.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Allow_errors'
      - $ref: '#/components/parameters/Context_names_get'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Destination_file_system_ids'
      - $ref: '#/components/parameters/Destination_file_system_names'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Origin_file_system_ids'
      - $ref: '#/components/parameters/Origin_file_system_names'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSystemJunctionsGetResponse'
        '207':
          description: 'Partial success. Some resources were returned, but there

            were also errors possibly preventing some resources from

            being returned.

            '
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSystemJunctionsGetResponse'
    post:
      tags:
      - File System Junctions
      summary: Pure Storage POST File-system-junctions
      description: Create a file system junction.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Context_names'
      - $ref: '#/components/parameters/Names_single_required'
      - $ref: '#/components/parameters/Origin_file_system_ids_single'
      - $ref: '#/components/parameters/Origin_file_system_names_single'
      - $ref: '#/components/parameters/Use_existing_directory'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileSystemJunction'
        required: true
        x-codegen-request-body-name: file-system-junction
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSystemJunctionsResponse'
      x-codegen-request-body-name: file-system-junction
    delete:
      tags:
      - File System Junctions
      summary: Pure Storage DELETE File-system-junctions
      description: 'Delete a file system junction.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Context_names'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content: {}
components:
  schemas:
    FileSystemJunction:
      allOf:
      - $ref: '#/components/schemas/_context'
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          destination_file_system:
            description: Reference to the destination file system.
            title: Reference
            allOf:
            - $ref: '#/components/schemas/_reference'
          junction_origin_path:
            description: 'The absolute path of the junction directory in the origin file system

              '
            type: string
          origin_file_system:
            description: Reference to the origin file system.
            title: Reference
            allOf:
            - $ref: '#/components/schemas/_reference'
            readOnly: true
          status:
            description: 'Status of the junction.

              Values include `CONNECTED` and `DISCONNECTED`.

              '
            type: string
            readOnly: true
    _errorContextResponseErrors:
      type: object
      properties:
        context:
          description: 'Contains information relating to the cause of this error,

            or the name of the object that was being processed when the error was encountered.

            This may be `null` for more general errors.

            '
          type: string
        location_context:
          description: 'Contains information relating to the context in which the request was executing

            when the error occurred.

            For example, this may be the name of an array in the same fleet.

            This may be `null` for more general errors, or if no explicit `context` parameter

            was provided with the request.

            '
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
        message:
          description: A description of the error which occurred.
          type: string
          example: Resource does not exist.
    _errorContextResponse:
      type: object
      properties:
        errors:
          description: The list of errors encountered when attempting to perform an operation.
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/_errorContextResponseErrors'
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name,

            such as volume name, pod name, snapshot name, and so on.

            '
          type: string
        resource_type:
          description: 'Type of the object (full name of the endpoint).

            Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

            `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

            `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

            `policies/snapshot`, etc.

            '
          type: string
          readOnly: true
      x-aliases:
      - _referenceWithFixedType
    _fixedReferenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
    FileSystemJunctionsResponse:
      type: object
      properties:
        items:
          description: A list of file system junction objects.
          type: array
          items:
            $ref: '#/components/schemas/FileSystemJunction'
    _context:
      type: object
      properties:
        context:
          description: 'The context in which the operation was performed.


            Valid values include a reference to any array which is a member of the same fleet

            or to the fleet itself.


            Other parameters provided with the request, such as names of volumes or snapshots,

            are resolved relative to the provided `context`.

            '
          readOnly: true
          title: FixedReference
          allOf:
          - $ref: '#/components/schemas/_fixedReference'
    _fixedReference:
      allOf:
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
    FileSystemJunctionsGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/FileSystemJunctionsResponse'
      - $ref: '#/components/schemas/_errorContextResponse'
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
  parameters:
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Origin_file_system_names_single:
      name: origin_file_system_names
      in: query
      description: 'A comma-separated list of origin file system names. Only one value is supported.

        This cannot be provided together with `origin_file_system_ids` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        maxLength: 1
        items:
          type: string
    Allow_errors:
      name: allow_errors
      in: query
      description: 'If set to `true`, the API will allow the operation to continue even if there are errors.

        Any errors will be returned in the `errors` field of the response.

        If set to `false`, the operation will fail if there are any errors.

        '
      schema:
        type: boolean
        default: false
    Origin_file_system_ids:
      name: origin_file_system_ids
      in: query
      description: 'A comma-separated list of origin file system IDs. If after filtering,

        there is not at least one resource that matches each of the elements,

        then an error is returned. This cannot be provided together with the

        `origin_file_system_names` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Context_names:
      name: context_names
      in: query
      description: 'Performs the operation on the context specified.


        If specified, the context names must be an array of size 1, and the single element

        must be the name of an array in the same fleet or the name of the fleet itself. If

        not specified, the context will default to the array that received this request.


        Other parameters provided with the request, such as names of volumes or snapshots,

        are resolved relative to the provided `context`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Origin_file_system_ids_single:
      name: origin_file_system_ids
      in: query
      description: 'A comma-separated list of origin file system IDs. Only one value is supported.

        This cannot be provided together with the `origin_file_system_names` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        maxLength: 1
        items:
          type: string
    Origin_file_system_names:
      name: origin_file_system_names
      in: query
      description: 'A comma-separated list of origin file system names. If there is not

        at least one resource that matches each of the elements, then an error

        is returned. This cannot be provided together with `origin_file_system_ids`

        query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Destination_file_system_ids:
      name: destination_file_system_ids
      in: query
      description: 'A comma-separated list of destination file system IDs. If after filtering,

        there is not at least one resource that matches each of the elements,

        then an error is returned. This cannot be provided together with the

        `destination_file_system_names` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Context_names_get:
      name: context_names
      in: query
      description: 'Performs the operation on the unique contexts specified.


        If specified, each context name must be the name of an array in the same fleet or

        the name of the fleet itself.


        If not specified, the context will default to the array that received this request.


        Other parameters provided with the request, such as names of volumes or snapshots,

        are resolved relative to the provided `context`.


        Enter multiple names in comma-separated format.

        For example, `name01,name02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Use_existing_directory:
      name: use_existing_directory
      in: query
      description: 'This parameter must be set to `true` if junction is created

        on an existing empty directory. Otherwise, it is assumed that

        junction directory doesn''t exist and a new directory will

        be created.

        '
      schema:
        type: boolean
        default: false
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Names_single_required:
      name: names
      in: query
      description: 'Performs the operation on the unique resource names specified.

        Only one value is supported.

        '
      required: true
      style: form
      explode: false
      schema:
        type: array
        maxLength: 1
        items:
          type: string
    Destination_file_system_names:
      name: destination_file_system_names
      in: query
      description: 'A comma-separated list of destination file system names. If there is not

        at least one resource that matches each of the elements, then an error

        is returned. This cannot be provided together with `destination_file_system_ids`

        query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
