openapi: 3.0.1
info:
  title: FlashArray REST Active Directory SNMP Agents API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: SNMP Agents
  description: 'Manages connections to Simple Network Management Protocol (SNMP) agents.

    '
paths:
  /api/2.52/snmp-agents:
    get:
      tags:
      - SNMP Agents
      summary: Pure Storage List SNMP Agent
      description: Displays the SNMP agent name and protocol attributes.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentGetResponse'
    patch:
      tags:
      - SNMP Agents
      summary: Pure Storage Modify SNMP Agent
      description: Modifies the name or the protocol attributes of the SNMP agent.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnmpAgentPatch'
        required: true
        x-codegen-request-body-name: snmp-agent
      responses:
        '200':
          description: Returns the newly updated SNMP agent object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentResponse'
      x-codegen-request-body-name: snmp-agent
  /api/2.52/snmp-agents/mib:
    get:
      tags:
      - SNMP Agents
      summary: Pure Storage List SNMP Agent MIB Text
      description: Displays the SNMP MIB text.
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Total_item_count'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentMibGetResponse'
  /api/2.26/snmp-agents:
    get:
      tags:
      - SNMP Agents
      summary: Pure Storage GET Snmp-agents
      description: List SNMP agent attributes.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset_2'
      - $ref: '#/components/parameters/Sort_2'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentGetResponse'
    patch:
      tags:
      - SNMP Agents
      summary: Pure Storage PATCH Snmp-agents
      description: Modify SNMP agent attributes.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnmpAgent_2'
        required: true
        x-codegen-request-body-name: snmp-agent
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentResponse'
      x-codegen-request-body-name: snmp-agent
  /api/2.26/snmp-agents/mib:
    get:
      tags:
      - SNMP Agents
      summary: Pure Storage GET Snmp-agents-mib
      description: 'List the SNMP MIB text.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpAgentMibResponse'
components:
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The starting position based on the results of the query

        in relation to the full set of response objects returned.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset_2:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort_2:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Total_item_count:
      name: total_item_count
      in: query
      description: 'If set to `true`, the `total_item_count` matching the

        specified query parameters is calculated and returned in

        the response. If set to `false`, the `total_item_count`

        is `null` in the response. This may speed up queries

        where the `total_item_count` is large. If not specified,

        defaults to `false`.

        '
      schema:
        type: boolean
    Sort:
      name: sort
      in: query
      description: "Sorts the response objects by the specified fields. Sorting can be applied to any field name\n in the response, in ascending order by default, or in descending order by prefixing the\n field name with a minus sign (-). Multiple fields can be specified as a comma-separated\n list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,\n the response will not include a continuation_token.\n"
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
  schemas:
    _snmp_v2c:
      description: 'The v2c configurations of SNMP.

        '
      type: object
      properties:
        community:
          description: 'Manager community ID under which Purity//FA is to communicate with the specified managers.

            '
          type: string
          maxLength: 32
          example: '****'
    SnmpAgentMibGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SnmpAgentMibResponse'
    SnmpAgentResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SnmpAgent'
    SnmpAgentGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/SnmpAgentResponse'
    SnmpAgent_2:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - type: object
        properties:
          engine_id:
            description: 'An SNMP agent''s adminstration domain unique name.

              '
            type: string
            maxLength: 32
            readOnly: true
            example: 80009e2205d7c0bd31fef5b87f4f44da
          v2c:
            $ref: '#/components/schemas/_snmp_v2c_2'
          v3:
            $ref: '#/components/schemas/_snmp_v3_2'
          version:
            description: 'Version of the SNMP protocol to be used by an SNMP manager

              in communications with Purity''s SNMP agent.

              Valid values are `v2c` and `v3`.

              '
            type: string
            example: v3
    SnmpAgentMib:
      type: object
      properties:
        mib:
          description: MIB text.
          type: string
          readOnly: true
    _snmp_v3_2:
      description: 'The v3 configurations of SNMP.

        '
      type: object
      properties:
        auth_passphrase:
          description: 'Passphrase used by Purity to authenticate the array with the

            specified managers.

            '
          type: string
          example: '****'
        auth_protocol:
          description: 'Hash algorithm used to validate the authentication passphrase.

            Valid values are `MD5` and `SHA`.

            '
          type: string
          example: MD5
        privacy_passphrase:
          description: Passphrase used to encrypt SNMP messages.
          type: string
          example: '****'
        privacy_protocol:
          description: 'Encryption protocol for SNMP messages.

            Valid values are `AES` and `DES`.

            '
          type: string
          example: DES
        user:
          description: 'User ID recognized by the specified SNMP managers which Purity

            is to use in communications with them.

            '
          type: string
          example: User1
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    SnmpAgent:
      allOf:
      - $ref: '#/components/schemas/_builtInResourceNoId'
      - type: object
        properties:
          engine_id:
            description: 'The administration domain unique name of an SNMP agent.

              '
            type: string
            maxLength: 32
            readOnly: true
            example: 80009e2205d7c0bd31fef5b87f4f44da
          v2c:
            $ref: '#/components/schemas/_snmp_v2c'
          v3:
            $ref: '#/components/schemas/_snmp_v3'
          version:
            description: 'Version of the SNMP protocol to be used by Purity//FA in communications

              with the specified manager.

              Valid values are `v2c` and `v3`.

              '
            type: string
            example: v3
    _snmp_v3:
      description: 'The v3 configurations of SNMP.

        '
      type: object
      properties:
        auth_passphrase:
          description: 'Passphrase used by Purity//FA to authenticate the array with the specified managers.

            '
          type: string
          example: '****'
        auth_protocol:
          description: 'Hash algorithm used to validate the authentication passphrase.

            Valid values are `MD5` and `SHA`.

            '
          type: string
          example: MD5
        privacy_passphrase:
          description: Passphrase used to encrypt SNMP messages.
          type: string
          example: '****'
        privacy_protocol:
          description: 'Encryption protocol for SNMP messages.

            Valid values are `AES` and `DES`.

            '
          type: string
          example: DES
        user:
          description: 'User ID recognized by the specified SNMP managers which Purity//FA

            is to use in communications with them.

            '
          type: string
          example: User1
    SnmpAgentPatch:
      allOf:
      - $ref: '#/components/schemas/_builtInResourceNoId'
      - type: object
        properties:
          engine_id:
            description: 'The administration domain unique name of an SNMP agent.

              '
            type: string
            maxLength: 32
            readOnly: true
            example: 80009e2205d7c0bd31fef5b87f4f44da
          v2c:
            $ref: '#/components/schemas/_snmp_v2c'
          v3:
            $ref: '#/components/schemas/_snmp_v3_patch'
          version:
            description: 'Version of the SNMP protocol to be used by Purity//FA in communications

              with the specified manager.

              Valid values are `v2c` and `v3`.

              '
            type: string
            example: v3
    _snmp_v2c_2:
      description: 'The v2c configurations of SNMP.

        '
      type: object
      properties:
        community:
          description: 'Manager community ID under which Purity is to communicate with

            the specified managers.

            '
          type: string
          maxLength: 32
          example: '****'
    SnmpAgentMibResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SnmpAgentMib'
    _snmp_v3_patch:
      description: 'The v3 configurations of SNMP.

        '
      type: object
      properties:
        auth_passphrase:
          description: 'Passphrase used by Purity//FA to authenticate the array with the specified managers.

            '
          type: string
          maxLength: 32
          example: '********'
        auth_protocol:
          description: 'Hash algorithm used to validate the authentication passphrase.

            Valid values are `MD5` and `SHA`.

            '
          type: string
          example: MD5
        privacy_passphrase:
          description: Passphrase used to encrypt SNMP messages.
          type: string
          minLength: 8
          maxLength: 63
          example: '********'
        privacy_protocol:
          description: 'Encryption protocol for SNMP messages.

            Valid values are `AES` and `DES`.

            '
          type: string
          example: DES
        user:
          description: 'User ID recognized by the specified SNMP managers which Purity//FA

            is to use in communications with them.

            '
          type: string
          example: User1
    _builtInResourceNoId:
      description: 'A built-in resource. Many are singletons predefined by Purity (e.g., support

        settings). Some correspond to a piece of software, like an app, or hardware,

        like a controller. Others are created by the system in response to some event

        (e.g., alerts, audit records).


        Typically, a user can''t create, delete or rename a built-in resource. A few

        can be created or deleted, but not renamed because the names are meaningful

        to Purity (e.g., VIFs, file systems, file system snapshots, volume snapshot).

        '
      type: object
      properties:
        name:
          description: 'A locally unique, system-generated name. The name cannot be modified.

            '
          type: string
          readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token`

            query param to get the next page of data.

            If you use the continuation token to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The continuation token is generated if the limit is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        more_items_remaining:
          description: 'Returns a value of `true` if subsequent items can be retrieved.

            '
          type: boolean
          example: false
        total_item_count:
          description: 'The total number of records after applying all filter query parameters.

            The `total_item_count` will be calculated if and only if the corresponding

            query parameter `total_item_count` is set to `true`. If this query parameter

            is not set or set to `false`, a value of `null` will be returned.

            '
          type: integer
          format: int32
