openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Files API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Files
paths:
  /api/2.52/files:
    post:
      tags:
      - Files
      summary: Pure Storage Create a File Copy
      description: 'Creates a file copy from one path to another path.

        The `directory_ids`, `directory_names` or `paths` value must be specified.

        If the `directory_ids` or `directory_names` value is not specified, the file is copied to the

        source directory specified in the body params.

        The `paths` value refers to the path of the target file relative to the target directory.

        If `paths` value is not specified, the file will be copied to the relative path specified

        in `source_path` under the target directory.

        The `source_path` value refers to the path of the source file relative to the source directory.

        To overwrite an existing file, set the `overwrite` flag to `true`.

        '
      parameters:
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Directory_ids'
      - $ref: '#/components/parameters/Directory_names'
      - $ref: '#/components/parameters/Overwrite'
      - $ref: '#/components/parameters/Paths'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilePost'
        required: true
        x-codegen-request-body-name: source-file
      responses:
        '200':
          description: OK
          content: {}
      x-codegen-request-body-name: source-file
components:
  parameters:
    Directory_names:
      name: directory_names
      in: query
      description: 'Performs the operation on the managed directory names specified.

        Enter multiple full managed directory names in comma-separated format.

        For example, `fs:dir01,fs:dir02`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Overwrite:
      name: overwrite
      in: query
      description: 'If set to `true`,

        overwrites an existing object during an object copy operation.

        If set to `false` or not set at all and the target name is an existing object,

        the copy operation fails.

        Required if the `source` body parameter is set

        and the source overwrites an existing object during the copy operation.

        '
      schema:
        type: boolean
    Authorization:
      name: Authorization
      in: header
      description: 'Access token (in JWT format) required to use any API

        endpoint (except `/oauth2`, `/login`, and `/logout`)

        '
      schema:
        type: string
    Paths:
      name: paths
      in: query
      description: 'Target file path relative to the target directory.

        Enter multiple target file path in a comma-separated format.

        For example, `/dir1/dir2/file1,/dir3/dir4/file2`.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Directory_ids:
      name: directory_ids
      in: query
      description: 'Performs the operation on the unique managed directory IDs specified.

        Enter multiple managed directory IDs in comma-separated format.

        The `directory_ids` or `directory_names` parameter is required, but they cannot be set together.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
  schemas:
    FilePost:
      type: object
      properties:
        source:
          description: 'The source information of a file copy.

            '
          title: ReferenceWithType
          allOf:
          - $ref: '#/components/schemas/_referenceWithType'
        source_path:
          description: 'The source file path relative to the source directory.

            '
          type: string
    _referenceWithType:
      allOf:
      - $ref: '#/components/schemas/_reference'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

              `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

              `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

              `policies/snapshot`, etc.

              '
            type: string
      x-aliases:
      - _reference
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name, such as volume name, pod name,

            snapshot name, and so on.

            '
          type: string
      x-aliases:
      - _referenceWithoutType
