openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Resiliency Groups API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Resiliency Groups
  description: 'Resiliency groups display pairs of nodes where HA is enabled.

    '
paths:
  /api/2.26/resiliency-groups:
    get:
      tags:
      - Resiliency Groups
      summary: Pure Storage GET Resiliency-groups
      description: Display all array resiliency groups.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResiliencyGroupGetResponse'
  /api/2.26/resiliency-groups/members:
    get:
      tags:
      - Resiliency Groups
      summary: Pure Storage GET Resiliency-groups/members
      description: List membership associations between resiliency groups and nodes added to the array.
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Member_ids'
      - $ref: '#/components/parameters/Member_names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Resiliency_group_ids'
      - $ref: '#/components/parameters/Resiliency_group_names'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              description: Supplied by client during request or generated by server.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResiliencyGroupMemberGetResponse'
components:
  parameters:
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Resiliency_group_names:
      name: resiliency_group_names
      in: query
      description: 'A comma-separated list of resiliency group names.

        If there is not at least one resource that matches each of the

        elements of `resiliency_group_names`, then an error is returned.

        This cannot be provided in conjunction with the `resiliency_group_ids` parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Member_ids:
      name: member_ids
      in: query
      description: 'A comma-separated list of member IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `member_ids`, then an error is returned.

        This cannot be provided together with the `member_names` query parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Member_names:
      name: member_names
      in: query
      description: 'A comma-separated list of member names.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
    Resiliency_group_ids:
      name: resiliency_group_ids
      in: query
      description: 'A comma-separated list of resiliency group IDs.

        If there is not at least one resource that matches each of the

        elements of `resiliency_group_ids`, then an error is returned.

        This cannot be provided in conjunction with the `resiliency_group_names` parameter.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
  schemas:
    Member:
      type: object
      properties:
        group:
          description: 'A reference to a group object that has the referenced member object

            as a member.

            '
          title: Reference
          allOf:
          - $ref: '#/components/schemas/_reference'
        member:
          description: 'A reference to an object that is a member of the referenced group.

            '
          title: Reference
          allOf:
          - $ref: '#/components/schemas/_reference'
    _reference:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
        name:
          description: 'The resource name,

            such as volume name, pod name, snapshot name, and so on.

            '
          type: string
        resource_type:
          description: 'Type of the object (full name of the endpoint).

            Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`,

            `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`,

            `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, and

            `policies/snapshot`, etc.

            '
          type: string
          readOnly: true
      x-aliases:
      - _referenceWithFixedType
    ResiliencyGroupMemberGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/ResiliencyGroupMemberResponse'
    _builtIn:
      type: object
      properties:
        id:
          description: 'A non-modifiable, globally unique ID chosen by the system.

            '
          type: string
          readOnly: true
        name:
          description: Name of the object (e.g., a file system or snapshot).
          type: string
          readOnly: true
    ResiliencyGroupGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/ResiliencyGroupResponse'
    ResiliencyGroupResponse:
      type: object
      properties:
        items:
          description: 'A list of resiliency group objects.

            '
          type: array
          items:
            $ref: '#/components/schemas/ResiliencyGroup'
    ResiliencyGroupMemberResponse:
      type: object
      properties:
        items:
          description: 'A list of resiliency group and member relationships.

            '
          type: array
          items:
            $ref: '#/components/schemas/Member'
    ResiliencyGroup:
      allOf:
      - $ref: '#/components/schemas/_builtIn'
      - description: 'A group of nodes that are configured to provide high availability

          in the case of failures within members of the group.

          '
        type: object
        properties:
          status:
            description: 'The status of the resiliency group.

              Valid values include `critical`, `healthy`, and `unhealthy`.

              '
            type: string
            readOnly: true
          status_details:
            description: 'The description of the status of the resiliency group if not healthy.

              '
            type: string
            readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
