openapi: 3.0.1
info:
  title: FlashArray REST Active Directory Policies - Password API
  version: '2.52'
  description: 'Active Directory configuration authenticates users for NFS using Kerberos or SMB using Kerberos

    or New Technology LAN Manager (NTLM). Active Directory is also used to authorize users by

    mapping identities across the NFS and SMB protocols by using LDAP queries.

    '
servers:
- url: /
tags:
- name: Policies - Password
  description: Manages password policies. These policies define requirements for user passwords complexity and login attempts.
paths:
  /api/2.26/password-policies:
    get:
      tags:
      - Policies - Password
      summary: Pure Storage List Password Policies
      description: 'Displays a list of password policies.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Continuation_token'
      - $ref: '#/components/parameters/Filter'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Names'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordPoliciesGetResponse'
    patch:
      tags:
      - Policies - Password
      summary: Pure Storage Modify Password Policies
      description: 'Modifies one or more password policies. To enable a policy, set `enabled=true`.

        To disable a policy, set `enabled=false`.

        '
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/Ids'
      - $ref: '#/components/parameters/Names'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordPolicy'
        required: true
        x-codegen-request-body-name: policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordPoliciesResponse'
      x-codegen-request-body-name: policy
components:
  schemas:
    _fixedReferenceWithoutType:
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified.

            '
          type: string
          readOnly: true
        name:
          description: 'The resource name, such as volume name, file system name,

            snapshot name, and so on.

            '
          type: string
          readOnly: true
      x-readOnly: true
    PasswordPoliciesResponse:
      type: object
      properties:
        items:
          description: 'Returns a list of all items after filtering.

            If applicable, the values are displayed for each name.

            '
          type: array
          items:
            $ref: '#/components/schemas/PasswordPolicy'
    PasswordPoliciesGetResponse:
      allOf:
      - $ref: '#/components/schemas/PageInfo'
      - $ref: '#/components/schemas/PasswordPoliciesResponse'
    PasswordPolicy:
      allOf:
      - $ref: '#/components/schemas/PolicyBaseRenameable'
      - type: object
        properties:
          enforce_dictionary_check:
            description: 'If `true`, test password against dictionary of known leaked passwords.

              Requires passwords longer than 6 characters.

              '
            type: boolean
            example: true
          enforce_username_check:
            description: 'If `true`, the username cannot be a substring of the password.

              Only applies to usernames of 4 characters and longer.

              '
            type: boolean
            example: true
          lockout_duration:
            description: 'The lockout duration, in milliseconds, if a user is locked out after reaching the maximum

              number of login attempts. Ranges from 1 second to 90 days.

              '
            type: integer
            format: int64
            minimum: 0
            maximum: 7776000000
            example: 3600000
          max_login_attempts:
            description: 'Maximum number of failed login attempts allowed before the user is locked out.

              '
            type: integer
            format: int32
            minimum: 0
            maximum: 100
            example: 10
          max_password_age:
            description: 'The maximum age of password before password change is required.

              Ranges from 1 day to 99999 days with 1 hour precision.

              0ms value means password expiration is disabled.

              Maximum age is always greater than the minimum password age.

              '
            type: integer
            format: int64
            minimum: 0
            maximum: 8639913600000
            example: 86400000
          min_character_groups:
            description: 'The minimum number of character groups ([a-z], [A-Z], [0-9], other) required to be present

              in a password.

              '
            type: integer
            format: int32
            minimum: 0
            maximum: 4
            example: 3
          min_characters_per_group:
            description: 'The minimum number of characters per group to count the group as present.

              '
            type: integer
            format: int32
            minimum: 0
            example: 1
          min_password_age:
            description: 'The minimum age, in milliseconds, of password before password change is allowed.

              Ranges from 0 ms to 7 days with precision to 1 hour.

              '
            type: integer
            format: int64
            minimum: 0
            maximum: 604800000
            example: 86400000
          min_password_length:
            description: 'Minimum password length. If not specified, defaults to 1.

              '
            type: integer
            format: int32
            minimum: 0
            maximum: 100
            example: 1
          password_history:
            description: 'The number of passwords tracked to prevent reuse of passwords.

              '
            type: integer
            format: int32
            minimum: 0
            maximum: 64
            example: 5
    _realmsReference:
      type: object
      properties:
        realms:
          description: 'Reference to the realms this resource belongs to.

            The value is set to empty array when the resource

            lives outside of a realm.

            '
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/_fixedReference'
    _fixedReference:
      allOf:
      - $ref: '#/components/schemas/_fixedReferenceWithoutType'
      - type: object
        properties:
          resource_type:
            description: 'Type of the object (full name of the endpoint).

              Valid values are the unique part of the resource''s REST endpoint.

              For example, a reference to a file system would have a

              `resource_type` of `file-systems`.

              '
            type: string
            readOnly: true
    _resource:
      description: 'An ordinary (as opposed to built-in) resource that can be created, named,

        renamed or deleted by the user. This might be a virtual resource (e.g., a

        file system), or correspond to something in the environment, like a host or a

        server.

        '
      type: object
      properties:
        id:
          description: 'A globally unique, system-generated ID.

            The ID cannot be modified and cannot refer to another resource.

            '
          type: string
          readOnly: true
        name:
          description: 'A user-specified name.

            The name must be locally unique and can be changed.

            '
          type: string
    PolicyBaseRenameable:
      allOf:
      - $ref: '#/components/schemas/_resource'
      - $ref: '#/components/schemas/_realmsReference'
      - type: object
        properties:
          enabled:
            description: 'If `true`, the policy is enabled. If not specified, defaults to `true`.

              '
            type: boolean
          is_local:
            description: Whether the policy is defined on the local array.
            type: boolean
            readOnly: true
          location:
            description: Reference to the array where the policy is defined.
            title: FixedReference
            allOf:
            - $ref: '#/components/schemas/_fixedReference'
          policy_type:
            description: 'Type of the policy. Valid values include `alert`, `audit`, `bucket-access`,

              `cross-origin-resource-sharing`, `network-access`, `nfs`, `object-access`,

              `s3-export`, smb-client`, `smb-share`, `ssh-certificate-authority`, and

              `telemetry-metrics`.

              '
            type: string
            readOnly: true
    PageInfo:
      type: object
      properties:
        continuation_token:
          description: 'Continuation token that can be provided in the `continuation_token` query

            param to get the next page of data.

            If you use the `continuation_token` to page through data you

            are guaranteed to get all items exactly once regardless of

            how items are modified. If an item is added or deleted during

            the pagination then it may or may not be returned.

            The `continuation_token` is generated if the `limit` is less

            than the remaining number of items, and the default sort is used

            (no sort is specified).

            '
          type: string
        total_item_count:
          description: Total number of items after applying `filter` params.
          type: integer
          format: int32
  parameters:
    Ids:
      name: ids
      in: query
      description: 'A comma-separated list of resource IDs.

        If after filtering, there is not at least one resource that matches

        each of the elements of `ids`, then an error is returned.

        This cannot be provided together with the `name` or `names` query parameters.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    Continuation_token:
      name: continuation_token
      in: query
      description: 'A token used to retrieve the next page of data

        with some consistency guaranteed.

        The token is a Base64 encoded value.

        Set `continuation_token` to the system-generated token taken from the `x-next-token`

        header field of the response.

        A query has reached its last page when the response does not include a token.

        Pagination requires the `limit` and `continuation_token`

        query parameters.

        '
      schema:
        type: string
    Offset:
      name: offset
      in: query
      description: 'The offset of the first resource to return from a collection.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Filter:
      name: filter
      in: query
      description: 'Narrows down the results to only the response objects

        that satisfy the filter criteria.

        '
      schema:
        type: string
    Names:
      name: names
      in: query
      description: 'Performs the operation on the unique names specified.

        Enter multiple names in comma-separated format.

        For example, `name01,name02`.


        If there is not at least one resource that matches

        each of the elements of `names`, then an error is returned,

        except when creating new resources.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    XRequestId:
      name: X-Request-ID
      in: header
      description: 'Supplied by client during request or generated by server.

        '
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: 'Limits the size of the response to the specified number of objects on each page.

        To return the total number of resources, set `limit=0`.

        The total number of resources is returned as a `total_item_count` value.

        If the page size requested is larger than the system maximum limit,

        the server returns the maximum limit, disregarding the requested page size.

        '
      schema:
        type: integer
        format: int32
        minimum: 0
      example: 10
    Sort:
      name: sort
      in: query
      description: 'Sort the response by the specified fields (in descending order if ''-''

        is appended to the field name).

        NOTE: If you provide a sort you will not get a `continuation_token` in

        the response.

        '
      style: form
      explode: false
      schema:
        type: array
        items:
          pattern: ^[a-z]+(_[a-z]+)*-?
          type: string
